version: '3.1'

services:
  postgres:
    image: postgres:12
    container_name: postgres-book-shelf
    network_mode: bridge
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fancyBook
      - POSTGRES_DB=postgres

  spring-book-shelf:
    image: spring-book-shelf:latest
    network_mode: bridge
    container_name: spring-book-shelf
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres-data: